spring.config.import=optional:file:.env[.properties]
spring.application.name=event_platform

# DataSource
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.data.web.pageable.serialization-mode=via-dto

spring.session.store-type=none

# JWT & OpenAI
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ntn8530@gmail.com
spring.mail.password=aqwbkloixnylyyum
spring.mail.test-connection=false

# JavaMail sender properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# REDIS CONFIGURATION
# ===============================
spring.data.redis.url=${REDIS_URL}

spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=Asia/Ho_Chi_Minh
server.servlet.session.cookie.max-age=604800
server.servlet.session.timeout=7d
#spring.jackson.serialization.write-dates-as-timestamps=false

json.fcm =${JSON_FCM}